# Generated by Django 3.1.1 on 2021-01-11 10:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loginpage', '0003_person'),
    ]

    operations = [
        migrations.CreateModel(
            name='GetInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('email', models.CharField(max_length=30)),
                ('aadhar', models.CharField(max_length=30)),
                ('mobile', models.CharField(max_length=30)),
                ('hotelname', models.CharField(max_length=30)),
            ],
        ),
        migrations.DeleteModel(
            name='Person',
        ),
    ]
